# 🖥️ Video / display
fullscreen=yes
screen=1
force-window=yes
vo=gpu-next
hwdec=nvdec
profile=gpu-hq
scale=ewa_lanczossharp
cscale=ewa_lanczossharp
video-sync=display-resample
interpolation=yes
autofit=100%

# 🔊 Audio
ao=pipewire
audio-buffer=0.2
volume=75

# 🎞️ Playback behavior
keep-open=yes
loop=yes
watch-later-options=sid

# 🎹 IPC (for external control)
input-ipc-server=/tmp/mpvsocket

# 🎨 Subtitles
sub-ass-override=yes
sub-color=1.0/0.9/0.4
sub-border-color=0.0/0.0/0.0
sub-border-size=5
sub-font-size=55
sub-bold=yes
sub-font=Roboto
sub-ass-use-video-data=all
sub-auto=fuzzy
sub-file-paths=.

# 🌐 Language preferences
alang=jpn,japanese,en,eng
slang=en,eng,ru,rus,russian

# Screenshots
screenshot-template="%F_%wH-%wM-%wS_%04n"

#memo 
[dont-log-my-porn]
profile-cond=(function() local ignored, path = {"/mnt/store/media/", "/run/media/"}, get("path", "") path = ((path:find("^%a[%w.+-]-://") or path:find("^%a[%w.+-]-:%?")) and path:lower() or require "mp.utils".join_path(get("working-directory", ""), path)):sub(1, -get("filename", ""):len()-1):lower() for _, ig in ipairs(ignored) do if path:find(ig:lower(), 1, true) then return true end end end)()
profile-restore=copy-equal
script-opts-append=memo-enabled=no
