export ZSH="$HOME/.oh-my-zsh"

[[ -f "$HOME/.zshrc_custom" ]] && source "$HOME/.zshrc_custom"

zstyle ':omz:plugins:nvm' lazy yes

plugins=(
  nvm
  git 
  zsh-autosuggestions 
  zsh-syntax-highlighting 
  z 
  fzf
)

source $ZSH/oh-my-zsh.sh

# ─── Dotfiles ────────────────────────────────────────────────────────────────
# Load generic modules
for f in "$HOME/dotfiles/src/shell/modules"/*.zsh(.N); do
  source "$f"
done

# Load distro-specific config
if [[ -f /etc/os-release ]]; then
  . /etc/os-release

  distro_file="$HOME/dotfiles/src/shell/modules/distro/${ID}.zsh"

  [[ -f "$distro_file" ]] && source "$distro_file"
fi

eval "$(starship init zsh)"
. "$HOME/.deno/env"
