for_window [app_id="org.mozilla.firefox"] move to workspace 3, focus
for_window [app_id="brave-browser"] move to workspace 1, focus
for_window [app_id="chromium-browser"] move to workspace 4, focus

for_window [app_id="kitty"] move to workspace 2, focus
