set $ignored_apps (org\.gnome\.Calculator|xdg-desktop-portal-gtk|xfce-polkit)

assign [app_id="org.mozilla.firefox"] workspace 3
assign [app_id="brave-browser"]       workspace 1
assign [app_id="chromium-browser"]    workspace 4
assign [app_id="kitty"]               workspace 2

assign [app_id="^(?!$ignored_apps$).*" tiling] workspace 10
assign [class="^(?!$ignored_apps$).*"  tiling] workspace 10

for_window [app_id="org.gnome.Calculator"]    floating enable
for_window [app_id="xdg-desktop-portal-gtk"]  floating enable
for_window [app_id="xfce-polkit"]             floating enable
for_window [workspace="10"] layout tabbed

for_window [app_id=".*"] focus
for_window [class=".*"]  focus
