#!/usr/bin/sh

sxhkd &
spice-vdagent &
polybar bar1 &
xset r rate 200 35 &
setxkbmap -layout us,ru -option grp:win_space_toggle &
xrandr --output Virtual-1 --mode 2560x1080 &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width 2
bspc config window_gap 12

bspc config split_ratio 0.52
bspc config borderless_monocle true
bspc config gapless_monocle true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
