#!/usr/bin/sh

MODULES_DIR="$(dirname "$(readlink -f "$0")")/modules"

[ -f "$HOME/.config/.bspwm_displays" ] && . "$HOME/.config/.bspwm_displays"

. "$MODULES_DIR/init.sh"
. "$MODULES_DIR/config.sh"

[ -f "$HOME/.config/.bspwm_settings" ] && . "$HOME/.config/.bspwm_settings"
