#!/usr/bin/sh

MODULES_DIR="$(dirname "$(readlink -f "$0")")/modules"

[ -f "$HOME/.bspwm_settings" ] && . "$HOME/.bspwm_settings"
[ -f "$HOME/.bspwm_displays" ] && . "$HOME/.bspwm_displays"

. "$MODULES_DIR/init.sh"
. "$MODULES_DIR/config.sh"
# . "$MODULES_DIR/keyboard.sh"
#
